### ISSUE TITLE
Can't get working with 30fps

### ISSUE THREAD

**Issue by cantonalex** [Inferencer/LipSick#20]
`extracting frames from video: /tmp/gradio/2026283a8dead122868293158b9fa514f5073269/SaveIG.mp4
Traceback (most recent call last):
  File "/home/user/app/inference.py", line 91, in <module>
    ds_feature = DSModel.compute_audio_feature(opt.driving_audio_path)
  File "/home/user/app/utils/deep_speech.py", line 43, in compute_audio_feature
    audio_sample_rate, audio = wavfile.read(audio_path)
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/scipy/io/wavfile.py", line 650, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/scipy/io/wavfile.py", line 521, in _read_riff_chunk
    raise ValueError(f"File format {repr(str1)} not understood. Only "
ValueError: File format b'\x00\x00\x00\x1c' not understood. Only 'RIFF' and 'RIFX' supported.
An error occurred: Command '['python', 'inference.py', '--source_video_path', '/tmp/gradio/2026283a8dead122868293158b9fa514f5073269/SaveIG.mp4', '--driving_audio_path', '/tmp/gradio/4a324a4a5cdf98a616bdb6c5b89d119ffc82e93d/New Recording 14.wav', '--pretrained_lipsick_path', './asserts/pretrained_lipsick.pth', '--deepspeech_model_path', './asserts/output_graph.pb', '--res_video_dir', './asserts/inference_result']' returned non-zero exit status 1.`

**Comment by cantonalex** [comment]
So far haven't been able to get the collab working either. Working on a Mac so clutching at straws here..

**Comment by cantonalex** [comment]
tried with different files on HF `raceback (most recent call last):
  File "/home/user/app/inference.py", line 88, in <module>
    video_size = extract_frames_from_video(opt.source_video_path, video_frame_dir)
  File "/home/user/app/inference.py", line 51, in extract_frames_from_video
    cv2.imwrite(result_path, frame)
cv2.error: OpenCV(4.9.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:786: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

An error occurred: Command '['python', 'inference.py', '--source_video_path', '/tmp/gradio/2015e5a35611909a7b21e9f60cd06be92edf63bb/set.mp4', '--driving_audio_path', '/tmp/gradio/542b09cae9673ee06f612aad5338cb217499d477/audio1.wav', '--pretrained_lipsick_path', './asserts/pretrained_lipsick.pth', '--deepspeech_model_path', './asserts/output_graph.pb', '--res_video_dir', './asserts/inference_result']' returned non-zero exit status 1.`

**Comment by Inferencer** [comment]
Yeah I think you messaged me on Discord, so I just ran the HF and it appears to run smoothly, just the input needs to be 25 fps mp4 and the audio needs to be a .wav you will get some warnings at the start but it will track the face eventually i prefer vids that are 1920x1080 but it can support vertical providing you don't use crazy sizes like 3k+ height 

```
===== Application Startup at 2024-05-27 17:48:35 =====

Running on local URL:  http://0.0.0.0:7860
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------

To create a public link, set `share=True` in `launch()`.
2024-05-27 20:00:00.839781: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-27 20:00:00.978662: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-27 20:00:00.985366: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cv2/../../lib64:
2024-05-27 20:00:00.985389: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-05-27 20:00:01.019011: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-05-27 20:00:01.845808: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cv2/../../lib64:
2024-05-27 20:00:01.845934: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cv2/../../lib64:
2024-05-27 20:00:01.845947: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
extracting frames from video: /tmp/gradio/1641439a293dfeb426d19c64525bbc440487b8d2/9.mp4
███████████████████████████████████████
█▄─▄███▄─▄█▄─▄▄─█─▄▄▄▄█▄─▄█─▄▄▄─█▄─█─▄█
██─██▀██─███─▄▄▄█▄▄▄▄─██─██─███▀██─▄▀██
▀▄▄▄▄▄▀▄▄▄▀▄▄▄▀▀▀▄▄▄▄▄▀▄▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀
Hang tight! We're processing your audio, which might take a little while depending on its length.
2024-05-27 20:00:13.091688: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2024-05-27 20:00:13.095497: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cv2/../../lib64:
2024-05-27 20:00:13.095651: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cv2/../../lib64:
2024-05-27 20:00:13.095826: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cv2/../../lib64:
2024-05-27 20:00:13.095977: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cv2/../../lib64:
2024-05-27 20:00:13.098810: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/cv2/../../lib64:
2024-05-27 20:00:13.098869: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-05-27 20:00:13.099346: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-27 20:00:14.312523: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
Tracking Face
Aligning frames with driving audio
Selecting five random reference images
loading pretrained model from: ./asserts/pretrained_lipsick.pth
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
synthesizing 0/232 frame 
```

**Comment by cantonalex** [comment]
do you plan to enhance 25fps

**Comment by Inferencer** [comment]
responded in discord but will update response here too for public availability, the 25fps issue arises from the audio model as it responds with 25fps data so our video must match that, I could implement something that converts the video to 25fps effectively which would solve the issue.

I will try to update the HF and collab with the new advanced features in the main repo such as automask for big square when I am available

**Comment by cantonalex** [comment]
Thanks! :)
