### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by badbabs** [Inferencer/LipSick#21]
Hi there, 

I'm running into an issue when processing my video. Everything starts fine and it begins to process until I am hit with an "access denied" "ERRNO13". I'm running visual studio code as an administrator as well as python as an administrator. 

I am using a .WAV file for the audio, and mp4 for the video.

I have also attached a screenshot of my folder structure which I believe to be ok. Any idea? Thank you so much. 

(base) PS C:\Users\madis\LipSick> conda activate LipSick
(LipSick) PS C:\Users\madis\LipSick> python app.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------
Extracting frames from video
Hang tight! We're processing your audio, which might take a little while depending on its length.
Tracking Face
Traceback (most recent call last):
  File "C:\Users\madis\LipSick\inference.py", line 97, in <module>
    video_landmark_data = np.array([load_landmark_dlib(frame) for frame in video_frame_path_list])
  File "C:\Users\madis\LipSick\inference.py", line 97, in <listcomp>
    video_landmark_data = np.array([load_landmark_dlib(frame) for frame in video_frame_path_list])
  File "C:\Users\madis\LipSick\inference.py", line 57, in load_landmark_dlib
    raise ValueError("No faces found in the image.")
ValueError: No faces found in the image.
An error occurred: Command '['python', 'inference.py', '--source_video_path', 'C:\\Users\\madis\\AppData\\Local\\Temp\\gradio\\7d6c826546791df8eb196725e6e44b5a3ba2b80e\\UPLOADMP4.mp4', '--driving_audio_path', 'C:\\Users\\madis\\AppData\\Local\\Temp\\gradio\\c33c344af7ad688d606d5f6b1c58cb495cf9795a\\WAV.wav', '--pretrained_lipsick_path', './asserts/pretrained_lipsick.pth', '--deepspeech_model_path', './asserts/output_graph.pb', '--res_video_dir', './asserts/inference_result', '--custom_reference_frames', '5,5,5,5,5', '--custom_crop_radius', '0', '--auto_mask']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1795, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1625, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 410, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio_client\utils.py", line 1006, in async_traverse
    new_obj[key] = await async_traverse(value, func, is_root)
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio_client\utils.py", line 1002, in async_traverse
    return await func(json_obj)
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 384, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 275, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 188, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\madis\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 120, in hash_file
    with open(file_path, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\madis\\LipSick'

**Comment by badbabs** [comment]
![Screenshot 2024-05-28 130821](https://github.com/Inferencer/LipSick/assets/170888194/0428c49e-03b4-4a40-b7fe-467e78f4f8fc)

**Comment by Inferencer** [comment]
The access denied comes up a lot when it runs into an error I haven't properly adjusted to respond with a print statement, the error that you facing is a result of no face detected in the video, unfortunately at this time I haven't implemented skippable frames or print statements of the frames it's no finding a face on.

If one frame fails to find a face at any part of the input vid it currently gives up, often in this case there is a single black frame at either the start or end of the video, might be worth extracting the frames to get a better visualisation of the offending frame.

**Comment by badbabs** [comment]
Thank you so much!
