### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\sd\\LipSick'

### ISSUE THREAD

**Issue by nitinmukesh** [Inferencer/LipSick#33]
Getting this error.
Using MP4 and WAV file as inputs

```
To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------
Please upload audio first.
Computing Crop Radius...
Traceback (most recent call last):
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "C:\sd\LipSick\app.py", line 25, in compute_crop_radius_stats
    _, _, _, most_common = calculate_crop_radius_statistics(video_file.name)
  File "C:\sd\LipSick\compute_crop_radius.py", line 42, in calculate_crop_radius_statistics
    raise ValueError("No valid crop radius values found.")
ValueError: No valid crop radius values found.
Traceback (most recent call last):
  File "C:\sd\LipSick\inference.py", line 6, in <module>
    import torch
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\torch\__init__.py", line 1504, in <module>
    from . import masked
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\torch\masked\__init__.py", line 3, in <module>
    from ._ops import (
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\torch\masked\_ops.py", line 11, in <module>
    from torch._prims_common import corresponding_real_dtype
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\torch\_prims_common\__init__.py", line 23, in <module>
    import sympy
ModuleNotFoundError: No module named 'sympy'
An error occurred: Command '['python', 'inference.py', '--source_video_path', 'C:\\Users\\nitin\\AppData\\Local\\Temp\\gradio\\8d6035a334a0fa94578c62ad678f1dfc8d509275\\INPUT.mp4', '--driving_audio_path', 'C:\\Users\\nitin\\AppData\\Local\\Temp\\gradio\\45402d44c314281ed5b0131115b31abe0719a2a6\\INPUT.wav', '--pretrained_lipsick_path', './asserts/pretrained_lipsick.pth', '--deepspeech_model_path', './asserts/output_graph.pb', '--res_video_dir', './asserts/inference_result', '--custom_reference_frames', '5,10,15,20,25', '--custom_crop_radius', '0', '--auto_mask']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1795, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1625, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 410, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio_client\utils.py", line 1006, in async_traverse
    new_obj[key] = await async_traverse(value, func, is_root)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio_client\utils.py", line 1002, in async_traverse
    return await func(json_obj)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 384, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 275, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 188, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 120, in hash_file
    with open(file_path, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\sd\\LipSick'
```

**Comment by nitinmukesh** [comment]
tried again after using updater

```
Already up to date.
Press any key to continue . . .
```

```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------
Traceback (most recent call last):
  File "C:\sd\LipSick\inference.py", line 6, in <module>
    import torch
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\torch\__init__.py", line 1504, in <module>
    from . import masked
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\torch\masked\__init__.py", line 3, in <module>
    from ._ops import (
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\torch\masked\_ops.py", line 11, in <module>
    from torch._prims_common import corresponding_real_dtype
  File "C:\Users\nitin\AppData\Roaming\Python\Python310\site-packages\torch\_prims_common\__init__.py", line 23, in <module>
    import sympy
ModuleNotFoundError: No module named 'sympy'
An error occurred: Command '['python', 'inference.py', '--source_video_path', 'C:\\Users\\nitin\\AppData\\Local\\Temp\\gradio\\8d6035a334a0fa94578c62ad678f1dfc8d509275\\INPUT.mp4', '--driving_audio_path', 'C:\\Users\\nitin\\AppData\\Local\\Temp\\gradio\\45402d44c314281ed5b0131115b31abe0719a2a6\\INPUT.wav', '--pretrained_lipsick_path', './asserts/pretrained_lipsick.pth', '--deepspeech_model_path', './asserts/output_graph.pb', '--res_video_dir', './asserts/inference_result', '--custom_reference_frames', '5,5,5,5,5', '--custom_crop_radius', '0', '--auto_mask']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1795, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1625, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 410, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio_client\utils.py", line 1006, in async_traverse
    new_obj[key] = await async_traverse(value, func, is_root)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio_client\utils.py", line 1002, in async_traverse
    return await func(json_obj)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 384, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 275, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 188, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 120, in hash_file
    with open(file_path, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\sd\\LipSick'
```

**Comment by nitinmukesh** [comment]
The following fixed it.
pip install sympy

@Inferencer 
Please add in environment.yml
