### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by nitinmukesh** [Inferencer/LipSick#35]
This issue surfaced again not sure why. It was working just fine.
Now even I installed again getting this error

```
To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------
Extracting frames from video
Tracking Face
Traceback (most recent call last):
  File "C:\tut\LipSick\inference.py", line 97, in <module>
    video_landmark_data = np.array([load_landmark_dlib(frame) for frame in video_frame_path_list])
  File "C:\tut\LipSick\inference.py", line 97, in <listcomp>
    video_landmark_data = np.array([load_landmark_dlib(frame) for frame in video_frame_path_list])
  File "C:\tut\LipSick\inference.py", line 57, in load_landmark_dlib
    raise ValueError("No faces found in the image.")
ValueError: No faces found in the image.
An error occurred: Command '['python', 'inference.py', '--source_video_path', 'C:\\Users\\nitin\\AppData\\Local\\Temp\\gradio\\97637379e5a6ba3ddadc5253762cad9fb92e464b\\FINAL.mp4', '--driving_audio_path', 'C:\\Users\\nitin\\AppData\\Local\\Temp\\gradio\\6a86cf7b2d8372e28ee01a7fb4f683e655352bda\\intro_audio.wav', '--pretrained_lipsick_path', './asserts/pretrained_lipsick.pth', '--deepspeech_model_path', './asserts/output_graph.pb', '--res_video_dir', './asserts/inference_result', '--custom_reference_frames', '5,5,5,5,5', '--custom_crop_radius', '0', '--activate_custom_frames', '--auto_mask']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1795, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 1625, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 410, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio_client\utils.py", line 1006, in async_traverse
    new_obj[key] = await async_traverse(value, func, is_root)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio_client\utils.py", line 1002, in async_traverse
    return await func(json_obj)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 384, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\blocks.py", line 275, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 188, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\nitin\miniconda3\envs\LipSick\lib\site-packages\gradio\processing_utils.py", line 120, in hash_file
    with open(file_path, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\tut\\LipSick'
```

**Comment by nitinmukesh** [comment]
So this is the issue and solution included in post.
Avoid blank frames.

https://github.com/Inferencer/LipSick/issues/21#issuecomment-2135802103
