### ISSUE TITLE
No file found in './asserts/inference_result\\pre_blend.mp4'

### ISSUE THREAD

**Issue by FenryrMKIII** [Inferencer/LipSick#36]
Hello, here is the stack trace.
What could I be doing wrong?

I have a 5  seconds video (.mp4) with a 5 seconds speech (.wav). 

`
Extracting frames from video
Tracking Face
Aligning frames with driving audio
Selecting reference images based on input or randomly if unspecified
Using reference frames at indices: [83, 82, 91, 35, 12]
If each value has +5 added do not be alarmed it will -5 later
Synthesizing 124/125 frameAuto Mask stage
Extracting frames from samelength video
Extracting frames from pre_blend video
Tracking Face of Lip-synced (LipSick) video please wait..
Traceback (most recent call last):
  File "C:\Users\Public\Projects\LipSick\utils\blend.py", line 131, in <module>
    main(args.samelength_video_path, args.pre_blend_video_path)
  File "C:\Users\Public\Projects\LipSick\utils\blend.py", line 39, in main
    blend_videos(same_length_dir, pre_blend_dir, samelength_path, pre_blend_path)
  File "C:\Users\Public\Projects\LipSick\utils\blend.py", line 121, in blend_videos
    os.remove(pre_blend_path)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: './asserts/inference_result\\pre_blend.mp4'
Complete
Result saved in ./asserts/inference_results
Thank you for using LipSick for your Lip-Sync needs.
`

**Comment by FenryrMKIII** [comment]
Ok. I don't know if I missed the instruction but here is how I solved this issue on my side.
Went to ffmpeg [website](https://ffmpeg.org/download.html) to download the windows executables. You can find ffmpeg executable in the bin folder of the download.

I placed ffmpeg executable at the root of the Github project. And that solved the above issue. Indeed, stepping into debugging I saw it was the step where the script calls ffmpeg that was the issue and that's how I made the connection to the missing exe. No error message more specific was thrown, if developer woud like to improve that. 

Hope this helps others !
