### ISSUE TITLE
Numpy and permission error

### ISSUE THREAD

**Issue by zachysaur** [Inferencer/LipSick#37]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
--------
Traceback (most recent call last):
  File "F:\SickLip\LipSick-main\inference.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
An error occurred: Command '['python', 'inference.py', '--source_video_path', 'C:\\Users\\ggrov\\AppData\\Local\\Temp\\gradio\\e0843b7025f888f763a65e1f24939e97fe5811f6\\2.mp4', '--driving_audio_path', 'C:\\Users\\ggrov\\AppData\\Local\\Temp\\gradio\\41c1952398745a3b0c886b2d05323a9c5318a094\\1.wav', '--pretrained_lipsick_path', './asserts/pretrained_lipsick.pth', '--deepspeech_model_path', './asserts/output_graph.pb', '--res_video_dir', './asserts/inference_result', '--custom_reference_frames', '5,5,5,5,5', '--custom_crop_radius', '0', '--auto_mask']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\blocks.py", line 1795, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\blocks.py", line 1625, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\processing_utils.py", line 410, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio_client\utils.py", line 1006, in async_traverse
    new_obj[key] = await async_traverse(value, func, is_root)
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio_client\utils.py", line 1002, in async_traverse
    return await func(json_obj)
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\processing_utils.py", line 384, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\blocks.py", line 275, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\processing_utils.py", line 188, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "F:\SickLip\LipSick-main\venv\lib\site-packages\gradio\processing_utils.py", line 120, in hash_file
    with open(file_path, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'F:\\SickLip\\LipSick-main'

**Comment by giandre** [comment]
I have the same identical problem. Is there a resolution?

**Comment by nitinmukesh** [comment]
Avoid blank frames / Frames which do not have face.

https://github.com/Inferencer/LipSick/issues/21#issuecomment-2135802103

So open the video in any video editor and remove blank, empty frames or frames which does not have face.
